- src/app/layout.tsx
- src/components/meta/Meta.tsx
This pull request introduces a new feature aimed at enhancing SEO capabilities by adding meta tags to the HTML code. The goal is to improve search engine visibility and provide better metadata for web crawlers.
- Added a new component Meta inside the new meta directory. 
- Added all the meta tags inside the next Head component.
SEO plays a crucial role in improving a website's discoverability. The addition of meta tags is in line with industry best practices and will contribute to improved search engine rankings.
> Added metatags for SEO

- src/app/projects/assets/projects.json
Modified projects.json and added some more element in the array.
> New projects added

- src/app/projects/assets/projects.json
- src/app/projects/assets/upcomingProjects.json
- added more projects in all projects data.
- added all new projects in upcoming projects data.
> refactor: update all projects and upcoming projects data.

- README.md
> refactor: update README.md file.

- .github/workflows/ci.yml
Added the ci.yml file for building the project when code is pushed into the main branch
> feat: add github actions

- .github/workflows/ci.yml
> Fix permissions

- README.md
- src/app/projects/components/ProjectCard.tsx
> Add  contributor

- src/app/projects/components/ProjectCard.tsx
Remove line and buttons when project/ upcoming projects  are NA
> UI changes under projects page

- README.md
- src/app/projects/components/ProjectCard.tsx
> Fix upcoming project section

- src/app/projects/components/ProjectCard.tsx
- src/app/projects/components/ProjectGrid.tsx
fix issues with upcoming projects
> fix issues with upcoming projects

- package.json
Added repo URL in package.json to run semantic release note
> fix: added repo url to package.json

- .github/workflows/ci.yml
- package.json
> Fix git actions 

- .github/workflows/ci.yml
- src/app/contributors/page.tsx
- src/app/projects/assets/contributors.json
- src/app/projects/components/ProjectCard.tsx
- src/constants/index.ts
- tsconfig.json
- updateProject.mjs
Added contributors page to FOSS website, first phase to list all the contributors
> Contributors page

- .github/workflows/ci.yml
Bug fixes related to contributors json update in github action work flow
> chore: update secret key for contributors json update

- .github/workflows/ci.yml
- updateProject.mjs
> Fix contributor issue 

- README.md
- updateProject.mjs
readme file updated, added Ashutosh's name under contributors
> chore: readme file updated

- .github/workflows/ci.yml
git restore stats.json issue fix
> fix: git restore stats.json

- .github/workflows/ci.yml
- src/app/packages/page.tsx
Added package ui spacing and ci schedule - cron  runs every night at 12 am UTC
> fix: package ui spacing and ci schedule

- src/app/packages/page.tsx
Fix dialog close model cross button icon to black in packages/page
> Fix dialog close model cross button icon to black in packages/page

- src/app/packages/page.tsx
- src/app/projects/assets/stats.json
- updateProject.mjs
> Fix blank package issue 

- src/app/packages/page.tsx
- src/app/projects/assets/stats.json
- updateProject.mjs
> Revert back code

- updateProject.mjs
Renamed package page-builder-core to page-builder
> fix: rename package page-builder-core to page-builder

- updateProject.mjs
fix package page-bulder download stats not showing
> fix: fix package page-bulder download stats not showing

- updateProject.mjs
> Add package title

- package-lock.json
- package.json
- public/images/social-media/docs.svg
- public/images/social-media/project.svg
- src/app/projects/assets/projects.json
- src/app/projects/components/ProjectCard.tsx
- src/app/projects/components/ProjectCount.tsx
- src/app/projects/components/ProjectGrid.tsx
- updateProject.mjs
> feat: add counters in projects

- src/app/projects/components/ProjectCard.tsx
- updateProject.mjs
> feat: add tags in projects

- src/app/projects/components/ProjectCard.tsx
> fix: fix spacing between contents

- src/app/contributors/page.tsx
- src/app/packages/page.tsx
- src/app/projects/components/ProjectCard.tsx
- src/app/projects/components/ProjectGrid.tsx
Fix paddings and changed colour for read more
Refs:[]
> fix: fix paddings for responsive

- updateScript/config.mjs
fix typo in ignix ui title config.mjs
> fix: fix typo in ignix ui title config.mjs
